### ISSUE TITLE
Want to Contribute

### ISSUE THREAD

**Issue by arpittyagi102** [DheerajGuptaa1/react_DG_eCom#1]
Hello, I would like to contribute to your project if you allow

**Comment by DheerajGuptaa1** [comment]
Yes please, let me know how can it be done?

**Comment by arpittyagi102** [comment]
Tell me any feature, function or page you want me to create for you, i will do it for you

**Comment by DheerajGuptaa1** [comment]
I want Login page of this App to be more comprehensive and Appealing.

Login page is coming while 'Add to Cart' Or 'Add to Favorite' button is clicked.

**Comment by arpittyagi102** [comment]
I think you have not yet updated the code, the code that is uploaded on github is empty, there are no pages, please have a look

**Comment by DheerajGuptaa1** [comment]
I uploaded it following the rule for Hosting a React App. It builds a file for Hosting. That built file given me just this, which I uploaded!

What can be done?

**Comment by arpittyagi102** [comment]
In React.js, we are supposed to upload all the files and folders to github except for the folder name "node_modules", everything else is required for hosting and sharing, for reference you can have a look on any react project on github

**Comment by DheerajGuptaa1** [comment]
These same files which on hosting shows nothing in-here on Github. Shows everything on netlify.

See the Link:
https://dg-ecom-react.netlify.app/

**Comment by arpittyagi102** [comment]
oh yes, its working fine on Netlify, i dont know why
